SCREEN_SIZE = WIDTH, HEIGHT = 500, 500
SPEED = 10
BLACK = (0, 0, 0)
LEFT, RIGHT, UP, DOWN, HALT = 0, 1, 2, 3, 4

ACTION_SIZE = 5
STATE_SIZE = 5

MINION_SPRITE_PATH = 'resources/enemy_sprite.bmp'
PLAYER_SPRITE_PATH = 'resources/blob.bmp'